# Generated by Django 2.0.3 on 2018-04-03 19:55

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image_top', models.ImageField(upload_to='')),
                ('image_side', models.ImageField(upload_to='')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField()),
                ('active', models.BooleanField(default=True)),
                ('create_tstamp', models.DateTimeField(auto_now_add=True)),
                ('update_tstamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chip',
                'verbose_name_plural': 'Chips',
            },
        ),
        migrations.CreateModel(
            name='ChipUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tstamp', models.DateTimeField()),
                ('unique_id', models.CharField(max_length=255)),
                ('data', models.BinaryField()),
                ('create_tstamp', models.DateTimeField(auto_now_add=True)),
                ('update_tstamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device Chip Upload',
                'verbose_name_plural': 'Device Chip Uploads',
                'db_table': 'chip_uploads',
            },
        ),
        migrations.CreateModel(
            name='TableEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tstamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('event_type', models.CharField(choices=[('DEALER', 'Dealer Clock In'), ('GAME', 'Game Clock In'), ('TABLE_CLOSE', 'Table Close')], max_length=255)),
                ('create_tstamp', models.DateTimeField(auto_now_add=True)),
                ('update_tstamp', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Table Event',
                'verbose_name_plural': 'Table Events',
                'db_table': 'table_events',
            },
        ),
        migrations.AlterModelOptions(
            name='chipevents',
            options={'verbose_name': 'Table Chip Drop Event', 'verbose_name_plural': 'Table Chip Drop Events'},
        ),
        migrations.AlterModelOptions(
            name='chipeventsdebug',
            options={'verbose_name': 'Table Chip Drop Events Debug', 'verbose_name_plural': 'Table Chip Drop Debug Events'},
        ),
        migrations.AlterModelOptions(
            name='devices',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name': 'Casino Game Type', 'verbose_name_plural': 'Casino Game Types'},
        ),
        migrations.AlterModelOptions(
            name='rfid',
            options={'verbose_name': 'RFID Token', 'verbose_name_plural': 'RFID Tokens'},
        ),
        migrations.AlterModelOptions(
            name='rfidevents',
            options={'verbose_name': 'RFID Scan Event', 'verbose_name_plural': 'RFID Scan Events'},
        ),
        migrations.AlterModelOptions(
            name='tables',
            options={'verbose_name': 'Casino Table', 'verbose_name_plural': 'Casino Tables'},
        ),
        migrations.RenameField(
            model_name='chipevents',
            old_name='table_id',
            new_name='table',
        ),
        migrations.RenameField(
            model_name='chipeventsdebug',
            old_name='chip_event_id',
            new_name='chip_event',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='table_id',
            new_name='table',
        ),
        migrations.RenameField(
            model_name='rfid',
            old_name='dealer_id',
            new_name='dealer',
        ),
        migrations.RenameField(
            model_name='rfid',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='rfidevents',
            old_name='rfid_id',
            new_name='rfid',
        ),
        migrations.RenameField(
            model_name='rfidevents',
            old_name='table_id',
            new_name='table',
        ),
        migrations.AddField(
            model_name='chipevents',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='chipevents',
            name='tstamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfidevents',
            name='update_tstamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tableevents',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Games'),
        ),
        migrations.AddField(
            model_name='tableevents',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.RFIDEvents'),
        ),
        migrations.AddField(
            model_name='tableevents',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Tables'),
        ),
        migrations.AddField(
            model_name='chipuploads',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tables'),
        ),
    ]
