# Generated by Django 2.0.3 on 2018-07-17 21:16

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180403_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='chipevents',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='chipuploads',
            name='data_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devices',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='chipevents',
            name='tstamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='chipuploads',
            name='data',
            field=models.FileField(upload_to='chips_raw/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='chipuploads',
            name='tstamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='chipuploads',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='games',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tableevents',
            name='tstamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tables',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
