# Generated by Django 2.0.3 on 2018-07-19 19:25

import chipcounting.api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180717_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidevents',
            name='tstamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='chipuploads',
            name='data',
            field=models.FileField(editable=False, upload_to=chipcounting.api.models.get_chip_upload_path),
        ),
        migrations.AlterField(
            model_name='chipuploads',
            name='tstamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='chipuploads',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rfid',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rfid',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Games'),
        ),
        migrations.AlterField(
            model_name='rfid',
            name='token_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
