# Generated by Django 2.0.7 on 2018-08-20 18:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180719_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='mender_id',
            new_name='name',
        ),
        migrations.AddField(
            model_name='devices',
            name='computer_vision_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='devices',
            name='last_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Last Update Image'),
        ),
        migrations.AddField(
            model_name='devices',
            name='ping_tstamp',
            field=models.DateTimeField(null=True, verbose_name='Last Ping Time'),
        ),
        migrations.AddField(
            model_name='devices',
            name='trained_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Trained Idle Image'),
        ),
        migrations.AlterField(
            model_name='rfidevents',
            name='rfid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.RFID'),
        ),
        migrations.AlterField(
            model_name='rfidevents',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Tables'),
        ),
    ]
