# Generated by Django 2.0.7 on 2018-08-20 21:39

import chipcounting.api.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180820_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='computer_vision_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='devices',
            name='last_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=chipcounting.api.models.get_device_last_image_upload_path, verbose_name='Last Update Image'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='ping_tstamp',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Last Ping Time'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='trained_image',
            field=models.ImageField(blank=True, null=True, upload_to=chipcounting.api.models.get_device_trained_image_upload_path, verbose_name='Trained Idle Image'),
        ),
    ]
