# Generated by Django 2.0.7 on 2018-08-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180820_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='computer_vision_config',
            field=models.TextField(default=''),
        ),
    ]
