# Generated by Django 2.0.7 on 2018-08-24 01:55

import chipcounting.api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180820_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chipeventsdebug',
            name='debug_data',
        ),
        migrations.RemoveField(
            model_name='chipeventsdebug',
            name='log_data',
        ),
        migrations.RemoveField(
            model_name='chipeventsdebug',
            name='results',
        ),
        migrations.AddField(
            model_name='chipeventsdebug',
            name='data',
            field=models.FileField(editable=False, null=True, upload_to=chipcounting.api.models.get_chip_debug_path),
        ),
        migrations.AddField(
            model_name='chipeventsdebug',
            name='data_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chipeventsdebug',
            name='message',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='chipeventsdebug',
            name='result',
            field=models.CharField(choices=[('WAIT', 'Waiting to be processed'), ('PROCESSED', 'Processed'), ('EMPTY', 'No Slide Drop Detected'), ('ERROR', 'Error')], default='WAIT', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='chipeventsdebug',
            name='chip_event',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ChipEvents'),
        ),
    ]
