# Generated by Django 2.0.7 on 2018-08-24 15:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180823_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='chipeventsdebug',
            name='table',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Tables'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chipeventsdebug',
            name='upload_tstamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 24, 15, 57, 34, 914027, tzinfo=utc), editable=False, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='chipeventsdebug',
            name='result',
            field=models.CharField(choices=[('WAIT', 'Waiting to be processed'), ('PROCESSED', 'Processed'), ('EMPTY', 'No Slide Drop Detected'), ('ERROR', 'Error')], default='WAIT', editable=False, max_length=255, verbose_name='Processing Result'),
        ),
    ]
