# Generated by Django 2.0.7 on 2018-08-24 16:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180824_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chipeventsdebug',
            name='chip_event',
        ),
        migrations.AddField(
            model_name='chipeventsdebug',
            name='chip_upload',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ChipUploads'),
        ),
        migrations.AlterField(
            model_name='chipeventsdebug',
            name='upload_tstamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 24, 16, 22, 6, 278816, tzinfo=utc), editable=False, verbose_name='Timestamp'),
        ),
    ]
