# Generated by Django 2.0.7 on 2018-08-25 14:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180824_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipevents',
            name='create_tstamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chipevents',
            name='tstamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='chipeventsdebug',
            name='create_tstamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chipeventsdebug',
            name='upload_tstamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 8, 25, 14, 18, 27, 108307, tzinfo=utc), editable=False, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='chipuploads',
            name='create_tstamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chipuploads',
            name='tstamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='rfidevents',
            name='create_tstamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='rfidevents',
            name='tstamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='tableevents',
            name='dealer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tableevents',
            name='game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Games'),
        ),
        migrations.AlterField(
            model_name='tableevents',
            name='tstamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
    ]
