# Generated by Django 2.0.7 on 2018-08-25 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180825_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipeventsdebug',
            name='upload_tstamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Timestamp'),
        ),
    ]
