# Generated by Django 2.0.7 on 2018-08-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180825_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='chipeventsdebug',
            name='unique_id',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-0000-000000000000', editable=False, verbose_name='Unique ID'),
            preserve_default=False,
        ),
    ]
