# Generated by Django 2.0.7 on 2018-08-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_chipeventsdebug_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableevents',
            name='source',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.RFIDEvents'),
        ),
    ]
