# Generated by Django 2.0.7 on 2018-08-27 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180827_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='chipuploads',
            name='device',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Devices'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='table',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Tables'),
        ),
    ]
