# Generated by Django 2.0.7 on 2018-08-27 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180827_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipuploads',
            name='device',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Devices'),
        ),
    ]
