# Generated by Django 2.0.7 on 2019-05-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180827_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVImageMasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.IntegerField(db_index=True, verbose_name='Mask Set ID')),
                ('camera', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], max_length=255)),
                ('chip_position', models.IntegerField(verbose_name='Chip Position')),
                ('mask', models.ImageField(upload_to='')),
                ('create_tstamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_tstamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Computer Vision Model Image Masks',
                'db_table': 'cv_image_masks',
            },
        ),
        migrations.CreateModel(
            name='CVModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('data', models.BinaryField(verbose_name='Model Binary File')),
                ('labels', models.TextField(verbose_name='Labels in JSON array format')),
                ('create_tstamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_tstamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Computer Vision Model',
                'verbose_name_plural': 'Computer Vision Models',
                'db_table': 'cv_models',
            },
        ),
    ]
