# Generated by Django 2.0.7 on 2019-05-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_cvimagemasks_cvmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvmodels',
            name='data',
            field=models.FileField(upload_to='', verbose_name='Model Binary File'),
        ),
    ]
